"English":
- 'src/en/**'

"Russian":
- 'src/ru/**'

"Ukrainian":
- 'src/ua/**'

"Scripts":
- 'scripts/**'

# My goodness gracious.
"Design":
- 'src/en/general-proposals/**'
- 'src/en/space-station-14/departments/atmos/proposals/**'
- 'src/en/space-station-14/departments/cargo-salvage/proposals/**'
- 'src/en/space-station-14/departments/command/proposals/**'
- 'src/en/space-station-14/departments/engineering/proposals/**'
- 'src/en/space-station-14/departments/medical/proposals/**'
- 'src/en/space-station-14/departments/science/proposals/**'
- 'src/en/space-station-14/departments/security/proposals/**'
- 'src/en/space-station-14/departments/service/proposals/**'
